### ISSUE TITLE
schema fixes

### ISSUE THREAD

**Issue by ameinhardt** [eclipse/unide.python#2]
Hi @bgusach ,
I have updated the schemas in the unide project as discussed in [#21](https://github.com/eclipse/unide/issues/21). Could you review and update your
[schemas](https://github.com/eclipse/unide.python/tree/master/schema)?
Actually, I would favor to have one place for the schemas. Is it possible to have them in the main repository only?

**Comment by ameinhardt** [comment]
newly published here:
https://github.com/eclipse/unide/tree/master/ppmp/ppmp-schema/src/main/resources/org/eclipse/iot/unide/ppmp/v2

**Comment by bgusach** [comment]
Hi @ameinhardt,

sure, I'll will update the code. And yeah, I think the main unide repo is the right place for this kind of information.

**Comment by ameinhardt** [comment]
nice! let me know how it goes. I see that as last code improvement for version unide [0.2.0](https://projects.eclipse.org/projects/iot.unide/releases/0.2.0)

**Comment by bgusach** [comment]
Hi @ameinhardt 

Just to be sure: we are dealing with a new specification, right? 

The previous spec was identified by the `content-spec` `urn:spec://eclipse.org/unide/measurement-message#v2` whereas the new one by `urn:spec://bosch.com/ppm/measurement-message#v2`. (The fact that the URN has completely changed but both have the `v2`  at the end is a little confusing to me).

And the schema defined by `urn:spec://bosch.com/ppm/measurement-message#v2` is documented in https://github.com/eclipse/unide/tree/master/ppmp/ppmp-schema/src/main/resources/org/eclipse/iot/unide/ppmp/v2 

Is this correct?

**Comment by ameinhardt** [comment]
Hi @bgusach,
good catch,! For sure that was not correct - it shall remain eclipse.org. That's why its also under that namespace (folder).
Would you regard the spec still as v2 fix after this commit? https://github.com/eclipse/unide/commit/c4cf9c28eddae09b85ffc893b5c07bc9fe9224ce

**Comment by bgusach** [comment]
Well... I am not sure. Is it? 

Was `v2` ever released officially?  (I thought so, but could be that you considered everything to be in beta status) 

If it `v2` was official, it must be immutable and the changes you did in https://github.com/eclipse/unide/issues/21 should result in a new version IMHO, since there were non-cosmetic changes (e.g. some fields are now mandatory).

**Comment by bgusach** [comment]
BTW, the bosch urn can be found on the website: https://www.eclipse.org/unide/specification/measurement-message/#p-2

**Comment by ameinhardt** [comment]
@bgusach : fixed the website.
It is released. Unfortunately, there were contradictions between diagram, text and json schema. It was not clear, which of theses artifacts is master. Now, everything should be aligned to the json schema (including its description fields).
I regard the updates as errata.

**Comment by bgusach** [comment]
@ameinhardt that's actually pretty reasonable. Ok, so `v2` it is.

By the way, I think we could generate the web documentation automatically from the schema json files, at least partially. With a single source of truth we could avoid this kind of issues.  If Python is fine, I think I can take care of it...

**Comment by ameinhardt** [comment]
it is auto-generated now
https://github.com/eclipse/unide/blob/8facb5257f7311d218c00009be72425b60726043/website/pages/specification/machine-message.vue

Table of contents:
https://github.com/eclipse/unide/blob/8facb5257f7311d218c00009be72425b60726043/website/components/schemaToc.vue

and the field definitions
https://github.com/eclipse/unide/blob/8facb5257f7311d218c00009be72425b60726043/website/components/schemaDetail.vue

**Comment by bgusach** [comment]
Ouch, I think you mentioned that but I had forgotten it =)

Nice work... 👍

**Comment by bgusach** [comment]
Hi @ameinhardt ,

I have removed the schemata from this repository. 

However, I will include them at some point again, but under the tests folder, and clearly stating that it is not authoritative (the source is and must be the main unide repo). The idea is to include schema validation in the tests, but at this moment I could not find a python library supporting jsonschema's draft6, so I will create a new issue and work on it  when that is resolved.

I'd say this issue is closed.

By the way, probably the schema json files in the main unide repo should have the schema id, right? something like `"$schema": "http://json-schema.org/draft-06/schema#"`

**Comment by ameinhardt** [comment]
just fyi, the schemas should be draft-4 compatible, if we remove some unnecessary "require: []" with empty array.

**Comment by bgusach** [comment]
That's actually pretty helpful... thanks.
